settings:
  legacy:
    force: false
    interval: 0s

schema:
  - name: user-api
    path: .
    commands:
      install:
        status: true
        method: go build -o app ./cmd/main.go
      run:
        status: true
        method: ./app
    watcher:
      extensions:
        - go
      paths:
        - .
      ignore_paths:
        - .envrc
        - .envrc.sample
        - .gitignore
        - go.mod
        - go.sum
