openapi: '3.0.0'

info:
  title: gran
  description: Group Servie API設計
  version: 0.1.0

servers:
  - url: http://localhost:8080/v1/groups
    description: 開発環境
  - url: https://api.16francs.work/v1/groups
    description: 検証環境

paths:
  /:
    get:
      summary: グループ一覧取得
      security:
        - BearerAuth: []
      responses:
        '200':
          $ref: '#/components/responses/Groups'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/Unkown'

    post:
      summary: グループ作成
      security:
        - BearerAuth: []
      requestBody:
        $ref: '#/components/requestBodies/CreateGroup'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/Unkown'

  /{groupId}:
    get:
      summary: グループ詳細取得
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: groupId
          schema:
            type: string
          required: true
          description: グループID
      responses:
        '200':
          $ref: '#/components/responses/Group'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Unkown'

    patch:
      summary: グループ編集
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: groupId
          schema:
            type: string
          required: true
          description: グループID
      requestBody:
        $ref: '#/components/requestBodies/UpdateGroup'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Unkown'

  /{groupId}/invite:
    post:
      summary: グループ招待
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: groupId
          schema:
            type: string
          required: true
          description: グループID
      requestBody:
        $ref: '#/components/requestBodies/InviteUsers'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Unkown'

  /{groupId}/join:
    post:
      summary: グループ参加
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: groupId
          schema:
            type: string
          required: true
          description: グループID
      responses:
        '200':
          description: OK
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Unkown'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  schemas:
    Error:
      title: エラーレスポンス
      type: object
      properties:
        status:
          type: integer
          description: HTTPステータスコード
        code:
          type: integer
          description: エラー管理用ステータスコード
        message:
          type: string
          description: エラーメッセージ
        errors:
          type: array
          description: エラー詳細
          items:
            properties:
              field:
                type: string
              message:
                type: string

  requestBodies:
    CreateGroup:
      description: グループ作成フォーム
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                description: グループ名
              description:
                type: string
                description: 説明
            required:
              - name

    UpdateGroup:
      description: グループ編集フォーム
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                description: グループ名
              description:
                type: string
                description: 説明
            required:
              - name

    InviteUsers:
      description: グループ招待フォーム
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              emails:
                type: array
                description: 招待メールアドレス一覧
                items:
                  type: string
                  format: date-time

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unkown:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Group:
      description: グループ招待レスポンス
      content:
        application/json:
          schema:
            properties:
              id:
                type: integer
                description: グループID
              name:
                type: string
                description: グループ名
              description:
                type: string
                description: グループ説明
              userIDs:
                type: array
                description: ユーザーReference一覧
                items:
                  type: string
              createdAt:
                type: string
                format: date-time
                description: グループ作成日時
              updatedAt:
                type: string
                format: date-time
                description: グループ更新日時

    Groups:
      description: グループ一覧レスポンス
      content:
        application/json:
          schema:
            properties:
              groups:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      description: グループID
                    name:
                      type: string
                      description: グループ名
                    description:
                      type: string
                      description: グループ説明
                    userIDs:
                      type: array
                      description: ユーザーReference一覧
                      items:
                        type: string
                    createdAt:
                      type: string
                      format: date-time
                      description: グループ作成日時
                    updatedAt:
                      type: string
                      format: date-time
                      description: グループ更新日時
