openapi: '3.0.0'

info:
  title: gran
  description: ToDo Servie API設計
  version: 0.1.0

servers:
  - url: http://localhost:8080/v1/todos
    description: 開発環境
  - url: https://api.16francs.work/v1/todos
    description: 検証環境

paths:
  /groups/{groupId}/boards:
    get:
      summary: ボード一覧
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: groupId
          schema:
            type: string
          required: true
          description: グループID
      responses:
        '200':
          $ref: '#/components/responses/Boards'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Unkown'

    post:
      summary: ボード作成
      security:
        - BearerAuth: []
      requestBody:
        $ref: '#/components/requestBodies/CreateBoard'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Unkown'

  /groups/{groupId}/boards/{boardId}:
    get:
      summary: ボード詳細
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: groupId
          schema:
            type: string
          required: true
          description: グループID
        - in: path
          name: boardId
          schema:
            type: string
          required: true
          description: ボードID
      responses:
        '200':
          $ref: '#/components/responses/Board'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Unkown'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  schemas:
    Error:
      title: エラーレスポンス
      type: object
      properties:
        status:
          type: integer
          description: HTTPステータスコード
        code:
          type: integer
          description: エラー管理用ステータスコード
        message:
          type: string
          description: エラーメッセージ
        errors:
          type: array
          description: エラー詳細
          items:
            properties:
              field:
                type: string
              message:
                type: string

  requestBodies:
    CreateBoard:
      description: ボード作成フォーム
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                description: ボード名
              groupId:
                type: string
                description: グループID
              isClosed:
                type: boolean
                description: ボードを非公開
              thumbnail:
                type: string
                format: base64
                description: サムネイル
              backgroundColor:
                type: string
                description: 背景色
              labels:
                type: array
                description: タグ
                items:
                  type: string
            required:
              - name
              - groupId

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unkown:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Boards:
      description: ボード一覧レスポンス
      content:
        application/json:
          schema:
            properties:
              boards:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      description: ボードID
                    groupId:
                      type: integer
                      description: グループID
                    name:
                      type: string
                      description: ボード名
                    isClosed:
                      type: string
                      description: 非公開設定
                    ThumbnailUrl:
                      type: string
                      description: サムネイルURL
                    BackgroundColor:
                      type: string
                      description: 背景色
                    labels:
                      type: array
                      description: ラベル一覧
                      items:
                        type: string
                    createdAt:
                      type: string
                      format: date-time
                      description: グループ作成日時
                    updatedAt:
                      type: string
                      format: date-time
                      description: グループ更新日時

    Board:
      description: ボード詳細レスポンス
      content:
        application/json:
          schema:
            properties:
              id:
                type: integer
                description: ボードID
              groupId:
                type: integer
                description: グループID
              name:
                type: string
                description: ボード名
              isClosed:
                type: string
                description: 非公開設定
              ThumbnailUrl:
                type: string
                description: サムネイルURL
              BackgroundColor:
                type: string
                description: 背景色
              labels:
                type: array
                description: ラベル一覧
                items:
                  type: string
              lists:
                type: array
                description: ボードリスト一覧
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: リストID
                    name:
                      type: string
                      description: リスト名
                    color:
                      type: string
                      description: カラー
                    tasks:
                      type: array
                      description: タスク一覧
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                            description: タスクID
                          name:
                            type: string
                            description: タスク名
                          description:
                            type: string
                            description: 説明
                          labels:
                            type: array
                            description: ラベル一覧
                            items:
                              type: string
                          deadlinedAt:
                            type: string
                            format: date-time
                            description: 期限
                          assignedUserIds:
                            type: array
                            description: アサインユーザID一覧
                            items:
                              type: string
              createdAt:
                type: string
                format: date-time
                description: グループ作成日時
              updatedAt:
                type: string
                format: date-time
                description: グループ更新日時
