openapi: '3.0.0'

info:
  title: gran
  description: User Servie API設計
  version: 0.1.0

servers:
  - url: http://localhost:8080/v1/users
    description: 開発環境
  - url: https://api.16francs.work/v1/users
    description: 検証環境

paths:
  /:
    post:
      summary: ユーザ登録
      requestBody:
        $ref: '#/components/requestBodies/CreateUser'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/Unkown'

  /profile:
    get:
      summary: プロフィール取得
      security:
        - BearerAuth: []
      responses:
        '200':
          $ref: '#/components/responses/Profile'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Unkown'

    patch:
      summary: プロフィール編集
      security:
        - BearerAuth: []
      requestBody:
        $ref: '#/components/requestBodies/UpdateProfile'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Unkown'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  schemas:
    Error:
      title: エラーレスポンス
      type: object
      properties:
        status:
          type: integer
          description: HTTPステータスコード
        code:
          type: integer
          description: エラー管理用ステータスコード
        message:
          type: string
          description: エラーメッセージ
        errors:
          type: array
          description: エラー詳細
          items:
            properties:
              field:
                type: string
              message:
                type: string

  requestBodies:
    CreateUser:
      description: ユーザ登録フォーム
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              email:
                type: string
                format: email
                description: Eメール
              password:
                type: string
                description: パスワード
              passwordConfirmation:
                type: string
                description: パスワード(確認用)
            required:
              - email
              - password
              - passwordConfirmation

    UpdateProfile:
      description: プロフィール編集フォーム
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                description: 氏名
              displayName:
                type: string
                description: 表示名
              email:
                type: string
                format: email
                description: Eメール
              phoneNumber:
                type: string
                description: 電話番号
              thumbnail:
                type: string
                format: byte
                description: サムネイル
              biography:
                type: string
                description: 自己紹介
            required:
              - name
              - displayName
              - email

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unkown:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Profile:
      description: プロフィールレスポンス
      content:
        application/json:
          schema:
            properties:
              id:
                type: string
                description: ユーザID
              name:
                type: string
                description: 氏名
              displayName:
                type: string
                description: 表示名
              email:
                type: string
                format: email
                description: Eメール
              phoneNumber:
                type: string
                description: 電話番号
              thumbnailUrl:
                type: string
                format: byte
                description: サムネイル
              biography:
                type: string
                description: 自己紹介
              groupIds:
                type: array
                description: 参加グループID一覧
                items:
                  type: string
                  format: uuid
              createdAt:
                type: string
                format: date-time
                description: ユーザ作成日時
              updatedAt:
                type: string
                format: date-time
                description: ユーザ更新日時
