version: 2
updates:
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  target-branch: develop
  labels:
  - client
  - javascript
  - dependabot
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.11.0
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  commit-message:
    prefix: chore
- package-ecosystem: npm
  directory: "/storybook"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  target-branch: develop
  labels:
  - storybook
  - javascript
  - dependabot
  ignore:
  - dependency-name: ts-loader
    versions:
    - 8.0.14
    - 8.0.15
    - 8.0.16
    - 8.0.17
    - 8.0.18
    - 8.1.0
    - 8.2.0
    - 9.1.0
  - dependency-name: fork-ts-checker-webpack-plugin
    versions:
    - 6.1.0
    - 6.1.1
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: sass-loader
    versions:
    - 10.1.1
  commit-message:
    prefix: chore
- package-ecosystem: gomod
  directory: "/api/user"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  target-branch: develop
  labels:
  - "api: User"
  - golang
  - dependabot
  ignore:
  - dependency-name: google.golang.org/api
    versions:
    - 0.37.0
    - 0.38.0
    - 0.39.0
    - 0.40.0
    - 0.41.0
    - 0.42.0
    - 0.43.0
    - 0.44.0
    - 0.45.0
  commit-message:
    prefix: chore
- package-ecosystem: gomod
  directory: "/api/group"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  target-branch: develop
  labels:
  - "api: Group"
  - golang
  - dependabot
  commit-message:
    prefix: chore
- package-ecosystem: gomod
  directory: "/api/todo"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  target-branch: develop
  labels:
  - "api: ToDo"
  - golang
  - dependabot
  ignore:
  - dependency-name: google.golang.org/api
    versions:
    - 0.37.0
    - 0.38.0
    - 0.39.0
    - 0.40.0
    - 0.41.0
    - 0.42.0
    - 0.43.0
    - 0.44.0
    - 0.45.0
  commit-message:
    prefix: chore
