version: '3.7'

services:
  proxy:
    container_name: gran_proxy
    build: ./container/proxy
    volumes:
      - ./container/proxy/envoy.yaml:/etc/envoy/envoy.yaml:cached
    ports:
      - 8080:8080
    command: envoy -c /etc/envoy/envoy.yaml

  user_api:
    container_name: gran_user_api
    build: ./container/api/user
    working_dir: /go/src/github.com/16francs/gran/api/user
    volumes:
      - ./api/user:/go/src/github.com/16francs/gran/api/user:cached
      - ./secret:/secret:cached
    environment:
      - PORT=8080
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    command: realize start

  group_api:
    container_name: gran_group_api
    build: ./container/api/group
    working_dir: /go/src/github.com/16francs/gran/api/group
    volumes:
      - ./api/group:/go/src/github.com/16francs/gran/api/group:cached
      - ./secret:/secret:cached
    environment:
      - PORT=8080
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    command: realize start

  todo_api:
    container_name: gran_todo_api
    build: ./container/api/todo
    working_dir: /go/src/github.com/16francs/gran/api/todo
    volumes:
      - ./api/todo:/go/src/github.com/16francs/gran/api/todo:cached
      - ./secret:/secret:cached
    environment:
      - PORT=8080
      - GROUP_API_URL=${GROUP_API_URL}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    command: realize start

  swagger:
    container_name: gran_swagger
    build: ./container/swagger
    ports:
      - 8000:8080
    tty: true
    stdin_open: true
