version: '3.7'

services:
  client:
    container_name: gran_client
    build: ./container/client
    working_dir: /client
    volumes:
      - ./client:/client:cached
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
    command: yarn dev -H 0.0.0.0 -p 3000

  proxy:
    container_name: gran_proxy
    build: ./container/proxy
    volumes:
      - ./container/proxy/envoy.yaml:/etc/envoy/envoy.yaml:cached
    ports:
      - 8080:8080
    command: envoy -c /etc/envoy/envoy.yaml

  user_api:
    container_name: gran_user_api
    build: ./container/api/user
    working_dir: /go/src/github.com/16francs/gran/api/user
    volumes:
      - ./api/user:/go/src/github.com/16francs/gran/api/user:cached
      - ./secret:/secret:cached
    environment:
      - PORT=8080
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    command: realize start

  storybook:
    container_name: gran_storybook
    build: ./container/storybook
    working_dir: /storybook
    volumes:
      - ./storybook:/storybook:cached
      - ./client:/client:cached
    ports:
      - 6006:6006
    tty: true
    stdin_open: true
    environment:
      - CLIENT_PATH=${CLIENT_PATH}
    command: yarn storybook

  swagger:
    container_name: gran_swagger
    build: ./container/swagger
    ports:
      - 8000:8080
    tty: true
    stdin_open: true
