version: '3.7'
services:
 client:
  container_name: gran
  build: ./container/client
  ports:
   - 3000:3000
  volumes:
   - ./client:/client
  tty: true
  stdin_open: true
  command:  yarn dev -H 0.0.0.0 -p 3000
  working_dir: /client
