openapi: '3.0.0'

info:
  title: gran
  description: ToDo Servie API設計
  version: 0.1.0

servers:
  - url: http://localhost:8080/v1/todos
    description: 開発環境

paths:
  /:
    post:
      summary: ボード作成
      security:
        - BearerAuth: []
      requestBody:
        $ref: '#/components/requestBodies/CreateBoard'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Unkown'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  schemas:
    Error:
      title: エラーレスポンス
      type: object
      properties:
        status:
          type: integer
          description: HTTPステータスコード
        code:
          type: integer
          description: エラー管理用ステータスコード
        message:
          type: string
          description: エラーメッセージ
        errors:
          type: array
          description: エラー詳細
          items:
            properties:
              field:
                type: string
              message:
                type: string

  requestBodies:
    CreateBoard:
      description: ボード作成フォーム
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                description: ボード名
              groupId:
                type: string
                description: グループID
              closed:
                type: boolean
                description: ボードを非公開
              tuhumbnailUrl:
                type: string
                description: サムネイルURL
              backgroundColor:
                type: string
                description: 背景色
              labels:
                type: array
                description: タグ
                items:
                  type: string
            required:
              - name
              - groupId

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unkown:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
