version: 1

update_configs:
  # Client
  - package_manager: javascript
    directory: /client
    update_schedule: live # npmライブラリに更新がかかったタイミングでプルリク
    target_branch: master # 開発中はとりあえずmaster
    default_labels:
      - client
      - javascript
      - dependabot
    allowed_updates:
      - match:
          update_type: all # 全てのライブラリの更新を許可
    version_requirement_updates: auto # package.jsonの更新は自動
    automerged_updates:
      - match:
          dependency_type: all
          update_type: semver:patch
    commit_message:
      prefix: chore

  # Storybook
  - package_manager: javascript
    directory: /storybook
    update_schedule: live
    target_branch: master
    default_labels:
      - storybook
      - javascript
      - dependabot
    allowed_updates:
      - match:
          update_type: all
    version_requirement_updates: auto
    automerged_updates:
      - match:
          dependency_type: all
          update_type: semver:patch
    automerged_updates:
      - match:
          dependency_type: development
          update_type: semver:patch
      - match:
          dependency_type: production
          update_type: semver:patch
    commit_message:
      prefix: chore

  # API (User Service)
  - package_manager: go:modules
    directory: /api/user
    update_schedule: daily
    target_branch: master
    default_labels:
      - "api: User"
      - golang
      - dependabot
    allowed_updates:
      - match:
          update_type: all
    automerged_updates:
      - match:
          dependency_type: all
          update_type: semver:patch
    commit_message:
      prefix: chore
