name: User API(Golang) Deploy to Staging
on:
  push:
    # paths:
    #   - 'api/user/**'
    branches:
      - master

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: asia-northeast1
  GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GCR_HOSTNAME: asia.gcr.io
  GCR_IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy_for_stg:
    name: Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install PyOpenSSL
        run: pip install pyopenssl

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: $GCP_SA_KEY
          service_account_email: $GCP_SA_EMAIL

      - name: Configure gcloud
        run: |
          gcloud config set project ${GCP_PROJECT_ID}
          gcloud config set run/platform managed
          gcloud config set run/region ${GCP_REGION}
          gcloud auth configure-docker

      - name: Docker Build
        run: |
          docker build \
            -f container/api/user/Docker.production \
            -t gran_stg_user_api \
            .

      - name: Attached Tag by GitHub hash
        run: |
          docker tag \
            gran_stg_user_api \
            ${GCR_HOSTNAME}/${GCP_PROJECT_ID}/gran_stg_user_api:${GCR_IMAGE_TAG}

      - name: Push Google Cloud Registry for Staging
        run: |
          docker push \
            ${GCR_HOSTNAME}/${GCP_PROJECT_ID}/gran_stg_user_api:${GCR_IMAGE_TAG}
