name: Terraform(stg) Test
on:
  pull_request:
    paths:
      - 'terraform/env/stg/**'
      - 'terraform/modules/**'

env:
  tf_version: 'latest'
  tf_working_dir: 'terraform/env/stg'
  tf_actions_comment: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJET_ID }}
  TERRAFORM_CREDENTIALS: ${{ secrets.TERRAFORM_CREDENTIALS }}
  TERRAFORM_BACKEND_ORGANIZATION: ${{ secrets.TERRAFORM_BACKEND_ORGANIZATION }}
  TERRAFORM_BACKEND_BUCKET: ${{ secrets.TERRAFORM_BUCKET }}

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: ${ env.tf_action_comment }
          tf_actions_subcommand: 'fmt'

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: ${ env.tf_action_comment }
          tf_actions_subcommand: 'init'
          args:
            -backend-config="organization="${{ env.TERRAFORM_BACKEND_ORGANIZATION }}"
            -backend-config="bucket=${{ env.TERRAFORM_BACKEND_BUCKET }}"
            -backend-config="prefix=terraform/staging"

      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: ${ env.tf_action_comment }
          tf_actions_subcommand: 'validate'

      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: ${ env.tf_action_comment }
          tf_actions_subcommand: 'plan'
        env:
          GOOGLE_CLOUD_KEYFILE_JSON: ${{ env.TERRAFORM_CREDENTIALS }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.TERRAFORM_CREDENTIALS }}
          TF_VAR_project_id: ${{ env.GCP_PROJECT_ID }}
